// Edit the property collection, translations and hero media here. No build is required.
window.SERENITY = {
  "brand": "SERENITY STAY",
  "map": {
    "clientId": "285lo0ir94"
  },
  "hero": {
    "type": "image",
    "src": "",
    "poster": "assets/mia-201-02.jpg",
    "interval": 7500,
    "slides": [
      {
        "src": "assets/mia-201-02.jpg",
        "label": "MIA 201 · SEOUL",
        "alt": "dining201"
      },
      {
        "src": "assets/mia-202-07.jpg",
        "label": "MIA 202 · SEOUL",
        "alt": "kitchen202"
      }
    ]
  },
  "stays": [
    {
      "id": "mia201",
      "name": "Mia 201",
      "city": "seoul",
      "status": "open",
      "guests": 13,
      "bedrooms": 3,
      "baths": 2,
      "cover": "assets/mia-201-01.jpg",
      "coverAlt": "tub201",
      "tag": "tubTag",
      "intro": "mia201Intro",
      "description": "mia201Description",
      "airbnb": "https://www.airbnb.co.kr/rooms/1726477983734680758?source_impression_id=p3_1788827550_P3N7F9DKiUkYHBjD",
      "amenities": [
        "privateTub",
        "wifi",
        "kitchen",
        "laundry",
        "elevator",
        "selfCheckin",
        "parking",
        "queen6"
      ],
      "photos": [
        [
          "assets/mia-201-02.jpg",
          "dining201"
        ],
        [
          "assets/mia-201-01.jpg",
          "tub201"
        ],
        [
          "assets/mia-201-05.jpg",
          "bed201"
        ],
        [
          "assets/mia-201-07.jpg",
          "kitchen201"
        ],
        [
          "assets/mia-201-06.jpg",
          "details201"
        ],
        [
          "assets/mia-201-03.jpg",
          "tub201"
        ],
        [
          "assets/mia-201-04.jpg",
          "dining201"
        ],
        [
          "assets/mia-201-08.jpg",
          "tub201"
        ]
      ],
      "headline": "headline201",
      "rooms": [
        [
          "bedroom1",
          "queen4Bunk"
        ],
        [
          "bedroom2",
          "queen1Room"
        ],
        [
          "bedroom3",
          "queen1Room"
        ]
      ],
      "highlights": [
        [
          "tubFeatureTitle",
          "tubFeatureCopy"
        ],
        [
          "diningFeatureTitle",
          "dining201Copy"
        ]
      ],
      "equipment": [
        [
          "kitchenEquipmentTitle",
          "kitchenEquipmentCopy"
        ],
        [
          "comfortTitle",
          "comfort201Copy"
        ]
      ],
      "location": null
    },
    {
      "id": "mia202",
      "name": "Mia 202",
      "city": "seoul",
      "status": "open",
      "guests": 7,
      "bedrooms": 2,
      "baths": 2,
      "cover": "assets/mia-202-07.jpg",
      "coverAlt": "kitchen202",
      "tag": "togetherTag",
      "intro": "mia202Intro",
      "description": "mia202Description",
      "airbnb": "https://www.airbnb.co.kr/rooms/1726520220054341394?source_impression_id=p3_1788827554_P3kuzdC6EDGPpYuI",
      "amenities": [
        "wifi",
        "kitchen",
        "laundry",
        "elevator",
        "selfCheckin",
        "parking",
        "queen3"
      ],
      "photos": [
        [
          "assets/mia-202-07.jpg",
          "kitchen202"
        ],
        [
          "assets/mia-202-02.jpg",
          "dining202"
        ],
        [
          "assets/mia-202-03.jpg",
          "details202"
        ],
        [
          "assets/mia-202-06.jpg",
          "bed202"
        ],
        [
          "assets/mia-202-08.jpg",
          "bed202"
        ],
        [
          "assets/mia-202-04.jpg",
          "details202"
        ],
        [
          "assets/mia-202-05.jpg",
          "dining202"
        ]
      ],
      "headline": "headline202",
      "rooms": [
        [
          "bedroom1",
          "queen2Bunk"
        ],
        [
          "bedroom2",
          "queen1Room"
        ]
      ],
      "highlights": [
        [
          "diningFeatureTitle",
          "dining202Copy"
        ],
        [
          "bathroomTitle",
          "bathroomCopy"
        ]
      ],
      "equipment": [
        [
          "kitchenEquipmentTitle",
          "kitchenEquipmentCopy"
        ],
        [
          "comfortTitle",
          "comfort202Copy"
        ]
      ],
      "location": null
    },
    {
      "id": "busan",
      "name": "Busan",
      "city": "busan",
      "status": "soon",
      "cover": "assets/busan.jpg",
      "coverAlt": "busanPhoto",
      "tag": "nextChapter",
      "intro": "busanIntro",
      "description": "busanDescription",
      "airbnb": null,
      "location": null
    }
  ],
  "copy": {
    "en": {
      "pageTitle": "Serenity Stay — A slower side of Korea",
      "pageDescription": "Thoughtfully composed stays in Seoul. Discover Mia 201 and Mia 202. Busan coming soon. Book through Airbnb.",
      "skip": "Skip to content",
      "navStays": "Our stays",
      "navStory": "Our philosophy",
      "navArea": "Locations",
      "navInfo": "Good to know",
      "language": "Language",
      "menu": "Open navigation",
      "closeMenu": "Close navigation",
      "findStay": "Find your stay",
      "heroLabel": "YOUR OWN LITTLE CORNER OF KOREA",
      "heroTitle": "<span class=\"hero-line\"><span>A little slower.</span></span><span class=\"hero-line\"><span><em>A little more you.</em></span></span>",
      "heroIntro": "Leave the hurry outside.<br>Find your own rhythm, in Korea.",
      "exploreStays": "Discover the stays",
      "scroll": "FOLLOW A SLOWER RHYTHM",
      "previous": "Previous photograph",
      "next": "Next photograph",
      "pause": "Pause slideshow",
      "play": "Play slideshow",
      "pauseVideo": "Pause video",
      "playVideo": "Play video",
      "welcomeLabel": "A NOTE FROM SERENITY",
      "welcomeTitle": "Some places ask you to do more.<br>Ours invite you to <em>simply be.</em>",
      "welcomeCopy": "An unhurried breakfast. A table full of familiar faces. The freedom to explore, and the comfort of coming back. This is your little corner of Korea.",
      "meetSerenity": "What makes a stay, Serenity?",
      "collectionLabel": "THE STAY INDEX",
      "collectionTitle": "A space.<br><em>All yours.</em>",
      "collectionCopy": "Choose a place. Picture your days.<br>Let the next story begin.",
      "allStays": "All stays",
      "seoul": "Seoul",
      "busan": "Busan",
      "soonShort": "SOON",
      "comingSoon": "Coming soon",
      "nextChapter": "THE NEXT CHAPTER",
      "tubTag": "PRIVATE SOAKING TUB",
      "togetherTag": "MADE FOR TOGETHER",
      "guests": "guests",
      "bedrooms": "bedrooms",
      "baths": "bathrooms",
      "upTo": "Up to",
      "exploreStay": "Explore the stay",
      "onAirbnb": "Airbnb",
      "bookAirbnb": "Check availability on Airbnb",
      "showing": "stays shown",
      "mia201Intro": "A generous space for your favorite people. Slow evenings, long dinners, and a soak all to yourself.",
      "mia202Intro": "A warm, intimate home for shared adventures. Make time for the small moments in between.",
      "busanIntro": "A new chapter, by the sea. The same Serenity, with a different horizon.",
      "mia201Description": "Gather in a warm ivory-and-wood apartment with three bedrooms, two bathrooms, and a private soaking tub. Six queen mattresses, including bunk beds, leave room for family and friends. A shared dining space brings everyone back together.",
      "mia202Description": "An inviting home for family and friends, with two bedrooms, two bathrooms, and three queen mattresses, including bunk beds. Settle into warm wood interiors and a shared dining space after a day exploring Seoul.",
      "busanDescription": "Our Busan stay is not open for reservations yet. The exact location, photographs of the property, and opening date will be shared here when ready.",
      "destinationPhoto": "Busan · destination photograph",
      "bookingNote": "Your stay, booked with peace of mind. All reservations and payments are handled through Airbnb.",
      "ritualCaption": "CLOSE THE DOOR. OPEN UP YOUR DAY.",
      "storyLabel": "THE ART OF FEELING AT HOME",
      "storyTitle": "The luxury<br>of <em>nothing planned.</em>",
      "storyCopy": "A little less on the itinerary.<br>A little more in the moment.",
      "value1": "Made to feel good.",
      "value1Copy": "Soft light, warm wood, and the comfort of a space that comes together naturally.",
      "value2": "Room for your people.",
      "value2Copy": "A table to gather around. Separate rooms to retreat to. A little of both worlds.",
      "value3": "A rhythm of your own.",
      "value3Copy": "Market mornings and unhurried evenings, with Seoul waiting just outside.",
      "detailsLabel": "THE SMALL STUFF IS THE BIG STUFF.",
      "detailsTitle": "Stay in<br><em>the moment.</em>",
      "detailsCopy": "Good mornings.<br>Even better memories.",
      "detail1": "A morning without a plan.",
      "detail2": "Rest comes naturally.",
      "detail3": "Little things. Lasting feelings.",
      "areaLabel": "A NEIGHBORHOOD FOR EVERY STAY",
      "areaTitle": "Find your<br><em>little corner.</em>",
      "areaDescription": "Every stay has its own neighborhood. Explore the location information for this home before planning your journey.",
      "mapLoading": "Loading this stay’s map…",
      "mapUnavailable": "The map is unavailable right now. Use the link below for this stay’s location information.",
      "openMap": "Open Naver Map",
      "mapRegion": "Selected stay’s location on Naver Map",
      "faqLabel": "BEFORE YOU ARRIVE",
      "faqTitle": "A few things<br><em>worth knowing.</em>",
      "q1": "How do I make a reservation?",
      "a1": "Choose your stay and follow the link to Airbnb. You'll find live availability, the full price, and cancellation terms there. Your reservation and payment are completed on Airbnb.",
      "q2": "When can I check in and out?",
      "a2": "Check-in is from 4 PM, and check-out is by 11 AM. Both Seoul stays offer self check-in. Your host will share arrival instructions through Airbnb.",
      "q3": "Which stay is right for my group?",
      "a3": "Mia 201 has 3 bedrooms, 2 bathrooms, and a private soaking tub, for up to 13 guests. Mia 202 has 2 bedrooms and 2 bathrooms, for up to 7 guests. Confirm the guest count and applicable extra-person fees on Airbnb.",
      "q4": "Is there anything else I should know?",
      "a4": "Our Seoul stays are smoke-free and do not allow pets or parties. Please keep noise down after 9 PM. You can find the complete house rules and contact the host on the Airbnb listing.",
      "q5": "When does the Busan stay open?",
      "a5": "Our Busan chapter is still taking shape. An opening date and reservation link will be added here when they're ready.",
      "closingLabel": "COME AS YOU ARE.",
      "closingTitle": "LET’S<br><em>STAY.</em>",
      "closingNote": "SEOUL, NOW. BUSAN, SOON.",
      "footerCopy": "Warm spaces. Shared moments.<br>Your own little corner of Korea.",
      "backTop": "Back to top",
      "footerBooking": "Reservations & payments via Airbnb",
      "madeIn": "A WARM WELCOME, FROM KOREA.",
      "close": "Close stay details",
      "checkTimes": "CHECK-IN 16:00 · CHECK-OUT 11:00",
      "dialogNote": "Opens Airbnb in a new tab. Final prices, guest limits, availability, and house rules are confirmed there.",
      "privateTub": "Private soaking tub",
      "wifi": "Wi-Fi",
      "kitchen": "Kitchen",
      "laundry": "Washer & dryer",
      "elevator": "Elevator",
      "selfCheckin": "Self check-in",
      "parking": "Free parking",
      "queen6": "6 queen mattresses",
      "queen3": "3 queen mattresses",
      "dining201": "Mia 201 · A table for togetherness",
      "tub201": "Mia 201 · Private soaking tub",
      "bed201": "Mia 201 · Restful bedroom",
      "kitchen201": "Mia 201 · Kitchen & laundry",
      "details201": "Mia 201 · Thoughtful little details",
      "dining202": "Mia 202 · Warm dining space",
      "kitchen202": "Mia 202 · Kitchen & dining",
      "details202": "Mia 202 · Everyday rituals",
      "bed202": "Mia 202 · Cozy queen bunk beds",
      "busanPhoto": "Gwangan Bridge in Busan; a destination photograph, not the upcoming property",
      "heroFootnote": "PERSONAL SPACES. SHARED STORIES.",
      "stayRail": "Explore stays. Swipe, scroll horizontally, or use the arrow keys.",
      "railHint": "ONE STAY AT A TIME. TAKE YOUR TIME.",
      "previousStay": "Previous stay",
      "nextStay": "Next stay",
      "stepInside": "Step inside Mia 201",
      "photoCredits": "Photo credits",
      "busanAnnouncement": "Our next chapter: Busan.",
      "previewBusan": "A first look",
      "notOpenYet": "Not yet open for reservations",
      "openingLater": "Opening details to be announced",
      "photoGallery": "Stay photographs",
      "stayInformation": "Stay information",
      "tabOverview": "Overview",
      "tabRooms": "Rooms",
      "tabAmenities": "Amenities",
      "tabGuide": "Good to know",
      "roomsTitle": "A little room for everyone.",
      "amenitiesTitle": "Settle right in.",
      "headline201": "Good company. A little indulgence.",
      "headline202": "Small moments, shared together.",
      "bedroom1": "Bedroom 01",
      "bedroom2": "Bedroom 02",
      "bedroom3": "Bedroom 03",
      "queen4Bunk": "4 queen mattresses in bunk-bed arrangements.",
      "queen2Bunk": "2 queen mattresses in a bunk-bed arrangement.",
      "queen1Room": "1 queen mattress. A separate room to unwind.",
      "beddingNote": "Some mattresses are on upper bunks. Review the photographs and confirm the arrangement with your host if accessibility or young children are a consideration. Final occupancy is confirmed on Airbnb.",
      "bathroomTitle": "Two bathrooms",
      "bathroomCopy": "Two bathrooms make shared mornings a little easier.",
      "tubFeatureTitle": "Your own soaking ritual",
      "tubFeatureCopy": "A large private soaking tub, framed by warm wood and soft light.",
      "diningFeatureTitle": "A table to come back to",
      "dining201Copy": "A generous dining table with 8 chairs and 4 additional chairs available.",
      "dining202Copy": "A shared dining table with 6 chairs and an extra stool.",
      "kitchenEquipmentTitle": "For easy mornings",
      "kitchenEquipmentCopy": "Induction hob, microwave, refrigerator and water purifier. Light cooking is welcome.",
      "comfortTitle": "Everyday comforts",
      "comfort201Copy": "65-inch TV, air conditioning, washer and dryer. A capsule coffee machine is also provided.",
      "comfort202Copy": "55-inch TV, air conditioning, washer and dryer.",
      "checkInLabel": "CHECK-IN",
      "checkOutLabel": "CHECK-OUT",
      "arrivalGuide": "Self check-in is available. Your host shares arrival instructions through Airbnb. Please confirm any special arrival requests with the host before booking.",
      "houseRulesTitle": "A thoughtful stay.",
      "ruleQuiet": "Please keep noise down after 9 PM. Parties are not permitted.",
      "ruleSmoke": "No smoking and no pets.",
      "ruleCooking": "Light cooking only. Please review the full kitchen rules on Airbnb.",
      "ruleSecurity": "A security camera is installed at the entrance. See the Airbnb listing for details.",
      "chooseMapStay": "Choose a stay to explore its location",
      "locationHeading": "Your location",
      "viewStayLocation": "View this stay’s location",
      "locationExact": "Property location",
      "locationArea": "Approximate area",
      "locationPending": "Location details pending",
      "locationSoon": "Location to be announced",
      "mapPending": "Location information will be added here. In the meantime, explore this stay’s neighborhood on Airbnb.",
      "mapSoon": "A new address, a new chapter. The location will be revealed with our opening details.",
      "mapExactNote": "This map shows the selected stay’s location. Check your Airbnb arrival instructions for entrance details.",
      "mapAreaNote": "This map shows the selected stay’s approximate area, not its exact address. Arrival details are shared through Airbnb after booking.",
      "mapPendingNote": "An exact location has not been published here for this stay. Your host will share arrival details through Airbnb.",
      "mapAirbnb": "Location details on Airbnb"
    },
    "zh": {
      "pageTitle": "Serenity Stay — 感受韩国的慢时光",
      "pageDescription": "探索首尔 Mia 201 和 Mia 202 温馨住宿，釜山新空间即将开启。通过 Airbnb 预订。",
      "skip": "跳至主要内容",
      "navStays": "我们的住宿",
      "navStory": "品牌理念",
      "navArea": "位置",
      "navInfo": "入住须知",
      "language": "语言",
      "menu": "打开导航",
      "closeMenu": "关闭导航",
      "findStay": "寻找心仪住宿",
      "heroLabel": "在韩国，找到属于你的角落",
      "heroTitle": "<span class=\"hero-line\"><span>慢一点，</span></span><span class=\"hero-line\"><span><em>更自在一点。</em></span></span>",
      "heroIntro": "把匆忙留在门外。<br>在韩国，找到自己的节奏。",
      "exploreStays": "探索住宿",
      "scroll": "跟随更从容的节奏",
      "previous": "上一张照片",
      "next": "下一张照片",
      "pause": "暂停轮播",
      "play": "播放轮播",
      "pauseVideo": "暂停视频",
      "playVideo": "播放视频",
      "welcomeLabel": "来自 SERENITY 的一封短信",
      "welcomeTitle": "有的地方，让你忙着探索。<br>我们更想邀你，<em>自在停留。</em>",
      "welcomeCopy": "一顿不赶时间的早餐，一桌熟悉的笑脸。自由探索，也安心归来。这是你在韩国的一处小小归所。",
      "meetSerenity": "是什么，让这里成为 Serenity？",
      "collectionLabel": "旅居空间一览",
      "collectionTitle": "一处空间，<br><em>属于你。</em>",
      "collectionCopy": "选一处喜欢的空间，想象在这里的日常。<br>让新的故事慢慢开始。",
      "allStays": "全部住宿",
      "seoul": "首尔",
      "busan": "釜山",
      "soonShort": "即将开启",
      "comingSoon": "即将开启",
      "nextChapter": "下一段旅程",
      "tubTag": "私人泡澡浴池",
      "togetherTag": "为相聚而设",
      "guests": "位房客",
      "bedrooms": "间卧室",
      "baths": "间浴室",
      "upTo": "最多",
      "exploreStay": "探索此住宿",
      "onAirbnb": "Airbnb",
      "bookAirbnb": "前往 Airbnb 查看可订日期",
      "showing": "处住宿已显示",
      "mia201Intro": "为家人与好友留足空间。一起享用晚餐，也享受只属于自己的泡澡时光。",
      "mia202Intro": "温馨自在的旅居空间，与亲友一同探索城市，也珍惜旅途中的小小时刻。",
      "busanIntro": "面向海洋，开启新篇章。不同的风景，熟悉的 Serenity。",
      "mia201Description": "象牙白与原木色交织的温暖公寓，设有三间卧室、两间浴室和私人泡澡浴池。共有六张大号床垫（包含上下铺），适合与亲友共享旅途时光。宽敞的餐桌让大家自在相聚。",
      "mia202Description": "适合家庭与好友的温馨公寓，设有两间卧室、两间浴室和三张大号床垫（包含上下铺）。结束一天的首尔探索，在原木色空间和舒适餐桌旁，慢慢放松。",
      "busanDescription": "釜山住宿尚未开放预订。具体位置、住宿照片与开业日期将于确认后公布。",
      "destinationPhoto": "釜山城市风景 · 非住宿实景",
      "bookingNote": "安心期待下一次旅行。所有预订与付款均通过 Airbnb 完成。",
      "ritualCaption": "关上门，打开属于你的时光。",
      "storyLabel": "像在家一样自在的艺术",
      "storyTitle": "不做计划，<br>也是一种<em>享受。</em>",
      "storyCopy": "行程，少安排一点。<br>当下，多感受一些。",
      "value1": "舒适，从感受开始。",
      "value1Copy": "柔和的光，温润的木，自然融为一体的舒适空间。",
      "value2": "为重要的人，留些空间。",
      "value2Copy": "一张共享的餐桌，几间可以独处的卧室。让亲密与自在，刚好平衡。",
      "value3": "找到自己的节奏。",
      "value3Copy": "从市场里的清晨，到悠闲的夜晚。首尔的日常，就在门外。",
      "detailsLabel": "小小的细节，大大的美好。",
      "detailsTitle": "停留在<br><em>美好当下。</em>",
      "detailsCopy": "自在的清晨，<br>难忘的回忆。",
      "detail1": "不赶时间的早晨。",
      "detail2": "安心休息，自然而然。",
      "detail3": "小细节，长久的温暖。",
      "areaLabel": "每间住宿，都有自己的街区",
      "areaTitle": "找到你的<br><em>小小天地。</em>",
      "areaDescription": "每间住宿都有自己的周边环境。规划行程前，请查看此房源的位置信息。",
      "mapLoading": "正在加载此房源的地图…",
      "mapUnavailable": "地图暂时无法加载，请通过下方链接查看此房源的位置信息。",
      "openMap": "打开 Naver 地图",
      "mapRegion": "所选房源的 Naver 地图",
      "faqLabel": "出发之前",
      "faqTitle": "让旅途<br><em>从容一些。</em>",
      "q1": "如何预订住宿？",
      "a1": "选择心仪住宿后，点击链接前往 Airbnb，查看实时可订日期、完整价格和取消政策。预订及付款均在 Airbnb 上完成。",
      "q2": "入住和退房时间是几点？",
      "a2": "入住时间为下午 4 点起，退房时间为上午 11 点前。两处首尔住宿均支持自助入住，房东将通过 Airbnb 发送详细指引。",
      "q3": "哪一处适合我的同行人数？",
      "a3": "Mia 201 设有三间卧室、两间浴室和私人泡澡浴池，最多接待 13 位房客。Mia 202 设有两间卧室和两间浴室，最多接待 7 位房客。请在 Airbnb 上确认人数限制及额外房客费用。",
      "q4": "还需要了解哪些入住规定？",
      "a4": "首尔住宿内禁止吸烟，不可携带宠物或举办派对。晚上 9 点后请保持安静。完整入住规则及联系房东的方式，请以 Airbnb 房源页面为准。",
      "q5": "釜山住宿什么时候开业？",
      "a5": "釜山的新空间正在筹备中。开业日期和预订链接确认后，将在这里更新。",
      "closingLabel": "带着真实的自己，来吧。",
      "closingTitle": "一起<br><em>停留。</em>",
      "closingNote": "现在，首尔。即将，釜山。",
      "footerCopy": "温暖的空间，共享的时光。<br>你在韩国的一处小小归所。",
      "backTop": "返回顶部",
      "footerBooking": "通过 Airbnb 预订与付款",
      "madeIn": "来自韩国的温暖欢迎。",
      "close": "关闭住宿详情",
      "checkTimes": "入住 16:00 · 退房 11:00",
      "dialogNote": "将在新标签页打开 Airbnb。最终价格、人数限制、可订日期和入住规则以 Airbnb 为准。",
      "privateTub": "私人泡澡浴池",
      "wifi": "无线网络",
      "kitchen": "厨房",
      "laundry": "洗衣机与烘干机",
      "elevator": "电梯",
      "selfCheckin": "自助入住",
      "parking": "免费停车",
      "queen6": "六张大号床垫",
      "queen3": "三张大号床垫",
      "dining201": "Mia 201 · 相聚的餐桌",
      "tub201": "Mia 201 · 私人泡澡浴池",
      "bed201": "Mia 201 · 舒适卧室",
      "kitchen201": "Mia 201 · 厨房与洗衣设施",
      "details201": "Mia 201 · 用心的小细节",
      "dining202": "Mia 202 · 温暖的用餐空间",
      "kitchen202": "Mia 202 · 厨房与餐厅",
      "details202": "Mia 202 · 日常的小仪式",
      "bed202": "Mia 202 · 温馨的大号上下铺",
      "busanPhoto": "釜山广安大桥城市风景，并非即将开业的住宿实景",
      "heroFootnote": "自在的空间，共享的故事。",
      "stayRail": "探索住宿。可左右滑动或使用方向键。",
      "railHint": "一次遇见一处空间。慢慢挑选。",
      "previousStay": "上一处住宿",
      "nextStay": "下一处住宿",
      "stepInside": "走进 Mia 201",
      "photoCredits": "照片署名",
      "busanAnnouncement": "下一站：釜山。",
      "previewBusan": "抢先了解",
      "notOpenYet": "尚未开放预订",
      "openingLater": "开业信息即将公布",
      "photoGallery": "房源照片",
      "stayInformation": "房源信息",
      "tabOverview": "概览",
      "tabRooms": "卧室",
      "tabAmenities": "设施",
      "tabGuide": "入住须知",
      "roomsTitle": "相聚，也有各自的空间。",
      "amenitiesTitle": "安心住下来。",
      "headline201": "相聚的时光，私享的惬意。",
      "headline202": "一起收藏日常的小美好。",
      "bedroom1": "卧室 01",
      "bedroom2": "卧室 02",
      "bedroom3": "卧室 03",
      "queen4Bunk": "上下铺布局，共 4 张大号双人床垫。",
      "queen2Bunk": "上下铺布局，共 2 张大号双人床垫。",
      "queen1Room": "1 张大号双人床垫，独立的休息空间。",
      "beddingNote": "部分床垫位于上铺。如同行者行动不便或有幼儿，请查看照片并与房东确认床铺安排。最终入住人数以 Airbnb 为准。",
      "bathroomTitle": "两间浴室",
      "bathroomCopy": "两间浴室，让大家的早晨更从容。",
      "tubFeatureTitle": "私享泡澡时光",
      "tubFeatureCopy": "大浴缸、温润木色与柔和灯光，留一段时间给自己。",
      "diningFeatureTitle": "围坐一桌的温暖",
      "dining201Copy": "宽敞餐桌配备 8 把椅子，另有 4 把备用椅。",
      "dining202Copy": "共享餐桌配备 6 把椅子和 1 张备用凳。",
      "kitchenEquipmentTitle": "轻松开启早晨",
      "kitchenEquipmentCopy": "配备电磁炉、微波炉、冰箱和净水器，可进行简单烹饪。",
      "comfortTitle": "日常的便利",
      "comfort201Copy": "65 英寸电视、空调、洗衣机和烘干机，另配备胶囊咖啡机。",
      "comfort202Copy": "55 英寸电视、空调、洗衣机和烘干机。",
      "checkInLabel": "入住时间",
      "checkOutLabel": "退房时间",
      "arrivalGuide": "支持自助入住。房东会通过 Airbnb 提供入住指引；如有特殊抵达需求，请在预订前与房东确认。",
      "houseRulesTitle": "安心相处的小约定。",
      "ruleQuiet": "晚上 9 点后请保持安静，不允许举办派对。",
      "ruleSmoke": "禁止吸烟，不允许携带宠物。",
      "ruleCooking": "仅限简单烹饪，完整厨房使用规则请查看 Airbnb。",
      "ruleSecurity": "入口处安装有监控摄像头，详情请查看 Airbnb 房源页面。",
      "chooseMapStay": "选择房源，查看位置",
      "locationHeading": "住宿位置",
      "viewStayLocation": "查看此房源的位置",
      "locationExact": "房源位置",
      "locationArea": "大致区域",
      "locationPending": "位置信息待更新",
      "locationSoon": "位置尚未公布",
      "mapPending": "位置信息将更新至此。您可以先在此房源的 Airbnb 页面了解周边区域。",
      "mapSoon": "新的地址，新的故事。位置将随开业信息一同公布。",
      "mapExactNote": "地图显示所选房源的位置。入口等详细信息请查看 Airbnb 入住指引。",
      "mapAreaNote": "地图显示所选房源的大致区域，并非准确地址。预订后，房东会通过 Airbnb 提供抵达信息。",
      "mapPendingNote": "此房源尚未在这里公布准确位置。房东将通过 Airbnb 提供入住信息。",
      "mapAirbnb": "在 Airbnb 查看位置"
    },
    "ko": {
      "pageTitle": "Serenity Stay — 한국에서 만나는 느린 쉼",
      "pageDescription": "서울 미아 201·202의 따뜻한 공간을 만나보세요. 부산은 오픈 준비 중입니다. 예약은 Airbnb에서 진행됩니다.",
      "skip": "본문 바로가기",
      "navStays": "우리의 공간",
      "navStory": "브랜드 이야기",
      "navArea": "숙소 위치",
      "navInfo": "이용 안내",
      "language": "언어",
      "menu": "메뉴 열기",
      "closeMenu": "메뉴 닫기",
      "findStay": "머물 곳 찾기",
      "heroLabel": "한국에서 만나는 나만의 쉼",
      "heroTitle": "<span class=\"hero-line\"><span>조금 더 느리게.</span></span><span class=\"hero-line\"><span><em>조금 더 나답게.</em></span></span>",
      "heroIntro": "서두름은 문밖에 두고,<br>한국에서 나만의 리듬을 찾아보세요.",
      "exploreStays": "공간 둘러보기",
      "scroll": "조금 더 느린 리듬을 따라서",
      "previous": "이전 사진",
      "next": "다음 사진",
      "pause": "슬라이드 일시정지",
      "play": "슬라이드 재생",
      "pauseVideo": "영상 일시정지",
      "playVideo": "영상 재생",
      "welcomeLabel": "세러니티가 전하는 작은 편지",
      "welcomeTitle": "더 많은 것을 하게 하는 여행 대신,<br>온전히 <em>나로 머무는 시간.</em>",
      "welcomeCopy": "서두르지 않는 아침 식사, 익숙한 얼굴로 채워진 테이블. 자유롭게 떠나고 편안하게 돌아오는 곳. 한국에서 만나는 당신의 작은 집입니다.",
      "meetSerenity": "무엇이 세러니티다운 머무름일까요?",
      "collectionLabel": "머무를 공간들",
      "collectionTitle": "하나의 공간,<br><em>오롯이 당신의 것.</em>",
      "collectionCopy": "마음에 드는 곳을 고르고, 그곳의 하루를 그려보세요.<br>새로운 이야기가 시작됩니다.",
      "allStays": "전체 공간",
      "seoul": "서울",
      "busan": "부산",
      "soonShort": "준비 중",
      "comingSoon": "오픈 준비 중",
      "nextChapter": "새로운 이야기",
      "tubTag": "프라이빗 자쿠지",
      "togetherTag": "함께라서 좋은 공간",
      "guests": "명",
      "bedrooms": "개 침실",
      "baths": "개 욕실",
      "upTo": "최대",
      "exploreStay": "공간 자세히 보기",
      "onAirbnb": "Airbnb",
      "bookAirbnb": "Airbnb에서 예약 가능일 확인",
      "showing": "개 공간 표시 중",
      "mia201Intro": "소중한 사람들과 함께하는 넉넉한 공간. 긴 저녁 식사와 오롯한 자쿠지의 여유를 만나보세요.",
      "mia202Intro": "함께하는 여행을 위한 아늑한 집. 여행 사이사이의 소소한 순간까지 편안하게.",
      "busanIntro": "바다 곁에서 시작하는 새로운 이야기. 다른 풍경, 같은 세러니티를 준비합니다.",
      "mia201Description": "아이보리와 우드톤이 어우러진 공간에 침실 3개, 욕실 2개, 프라이빗 자쿠지를 갖췄습니다. 이층침대를 포함한 퀸 매트리스 6개로 가족과 친구들이 함께 머물고, 넓은 다이닝 공간에서 하루를 나눌 수 있습니다.",
      "mia202Description": "가족과 친구들의 여행을 위한 따뜻한 공간입니다. 침실 2개, 욕실 2개, 이층침대를 포함한 퀸 매트리스 3개를 갖췄습니다. 서울에서의 하루를 보낸 뒤 우드톤 인테리어와 편안한 다이닝 공간에서 쉬어가세요.",
      "busanDescription": "부산 숙소는 아직 예약을 받지 않습니다. 정확한 위치, 실제 숙소 사진, 오픈 일정은 준비가 완료되면 공개할 예정입니다.",
      "destinationPhoto": "부산 여행지 사진 · 숙소 실사진 아님",
      "bookingNote": "예약부터 결제까지, Airbnb를 통해 편안하게 준비하세요.",
      "ritualCaption": "문을 닫고, 나만의 하루를 열어보세요.",
      "storyLabel": "집처럼 편안해지는 시간",
      "storyTitle": "아무 계획이<br>없어도 <em>좋은 하루.</em>",
      "storyCopy": "일정은 조금 덜 채우고,<br>지금 이 순간은 조금 더 깊게.",
      "value1": "기분 좋은 공간의 조건.",
      "value1Copy": "부드러운 빛과 따뜻한 나무. 자연스럽게 어우러지는 편안함을 생각합니다.",
      "value2": "소중한 사람들을 위한 여유.",
      "value2Copy": "함께 둘러앉을 테이블과 혼자 쉬어갈 침실. 두 가지 쉼이 함께합니다.",
      "value3": "나만의 리듬을 찾아서.",
      "value3Copy": "시장에서 시작하는 아침과 느긋한 저녁. 문밖에서 서울의 일상을 만나세요.",
      "detailsLabel": "작은 것들이 만드는 큰 차이.",
      "detailsTitle": "지금 이 순간에<br><em>머물러보세요.</em>",
      "detailsCopy": "기분 좋은 아침,<br>오래 남을 기억.",
      "detail1": "계획 없이 시작하는 아침.",
      "detail2": "자연스럽게 찾아오는 쉼.",
      "detail3": "작은 디테일, 오래 남는 마음.",
      "areaLabel": "머무는 곳마다, 새로운 동네",
      "areaTitle": "나만의 곳을<br><em>찾아보세요.</em>",
      "areaDescription": "숙소마다 주변 환경이 다릅니다. 여행을 계획하기 전 이 숙소의 위치 정보를 확인해 보세요.",
      "mapLoading": "이 숙소의 지도를 불러오고 있어요…",
      "mapUnavailable": "지금은 지도를 불러올 수 없습니다. 아래 링크에서 이 숙소의 위치 정보를 확인해 주세요.",
      "openMap": "네이버 지도 열기",
      "mapRegion": "선택한 숙소의 네이버 지도",
      "faqLabel": "여행을 떠나기 전에",
      "faqTitle": "알아두면<br><em>더 편안한 여행.</em>",
      "q1": "예약은 어떻게 하나요?",
      "a1": "원하는 공간을 선택한 뒤 Airbnb 링크로 이동하세요. 실시간 예약 가능일, 최종 요금, 취소 정책을 확인할 수 있으며 예약과 결제는 모두 Airbnb에서 진행됩니다.",
      "q2": "체크인과 체크아웃 시간은 언제인가요?",
      "a2": "체크인은 오후 4시부터, 체크아웃은 오전 11시까지입니다. 서울 두 숙소 모두 셀프 체크인이 가능하며 자세한 입실 방법은 호스트가 Airbnb로 안내합니다.",
      "q3": "우리 일행에게는 어떤 공간이 어울릴까요?",
      "a3": "미아 201은 침실 3개, 욕실 2개와 자쿠지를 갖추고 최대 13명까지 머물 수 있습니다. 미아 202는 침실 2개, 욕실 2개로 최대 7명까지 가능합니다. 최종 수용 인원과 추가 인원 요금은 Airbnb에서 확인해 주세요.",
      "q4": "그 외 알아두어야 할 사항이 있나요?",
      "a4": "서울 숙소는 실내 금연이며 반려동물과 파티는 허용되지 않습니다. 오후 9시 이후에는 소음을 줄여 주세요. 전체 이용 규칙과 호스트 문의는 Airbnb 숙소 페이지를 이용해 주세요.",
      "q5": "부산 숙소는 언제 오픈하나요?",
      "a5": "부산의 새로운 공간은 현재 준비 중입니다. 오픈 일정과 예약 링크가 확정되면 이곳에 안내하겠습니다.",
      "closingLabel": "있는 그대로, 편안하게.",
      "closingTitle": "우리,<br><em>머물러요.</em>",
      "closingNote": "지금은 서울, 곧 부산에서도.",
      "footerCopy": "따뜻한 공간, 함께하는 순간.<br>한국에서 만나는 나만의 작은 집.",
      "backTop": "맨 위로",
      "footerBooking": "예약 및 결제는 Airbnb에서",
      "madeIn": "한국에서 전하는 따뜻한 환대.",
      "close": "숙소 상세 닫기",
      "checkTimes": "체크인 16:00 · 체크아웃 11:00",
      "dialogNote": "Airbnb가 새 탭으로 열립니다. 최종 요금, 수용 인원, 예약 가능일, 이용 규칙은 Airbnb에서 확인해 주세요.",
      "privateTub": "프라이빗 자쿠지",
      "wifi": "와이파이",
      "kitchen": "주방",
      "laundry": "세탁기·건조기",
      "elevator": "엘리베이터",
      "selfCheckin": "셀프 체크인",
      "parking": "무료 주차",
      "queen6": "퀸 매트리스 6개",
      "queen3": "퀸 매트리스 3개",
      "dining201": "미아 201 · 함께 둘러앉는 식탁",
      "tub201": "미아 201 · 프라이빗 자쿠지",
      "bed201": "미아 201 · 편안한 침실",
      "kitchen201": "미아 201 · 주방과 세탁 공간",
      "details201": "미아 201 · 정성스러운 디테일",
      "dining202": "미아 202 · 따뜻한 다이닝 공간",
      "kitchen202": "미아 202 · 주방과 다이닝",
      "details202": "미아 202 · 일상의 작은 순간",
      "bed202": "미아 202 · 아늑한 퀸 이층침대",
      "busanPhoto": "부산 광안대교 여행지 사진으로, 오픈 예정 숙소의 실사진이 아닙니다",
      "heroFootnote": "나만의 공간, 함께 쌓는 이야기.",
      "stayRail": "숙소 탐색. 좌우로 밀거나 방향키로 이동할 수 있습니다.",
      "railHint": "한 번에 한 공간씩, 천천히 둘러보세요.",
      "previousStay": "이전 숙소",
      "nextStay": "다음 숙소",
      "stepInside": "미아 201 안으로",
      "photoCredits": "사진 출처",
      "busanAnnouncement": "다음 이야기는, 부산에서.",
      "previewBusan": "미리 만나보기",
      "notOpenYet": "아직 예약이 시작되지 않았어요",
      "openingLater": "오픈 일정은 추후 공개됩니다",
      "photoGallery": "숙소 사진 모음",
      "stayInformation": "숙소 상세 정보",
      "tabOverview": "소개",
      "tabRooms": "침실",
      "tabAmenities": "편의시설",
      "tabGuide": "이용 안내",
      "roomsTitle": "함께, 또 각자의 공간.",
      "amenitiesTitle": "편안히 머무를 수 있도록.",
      "headline201": "함께하는 시간, 온전한 여유.",
      "headline202": "작은 순간도 함께 나누는 곳.",
      "bedroom1": "침실 01",
      "bedroom2": "침실 02",
      "bedroom3": "침실 03",
      "queen4Bunk": "이층 침대 구조의 퀸 매트리스 4개.",
      "queen2Bunk": "이층 침대 구조의 퀸 매트리스 2개.",
      "queen1Room": "퀸 매트리스 1개가 있는 독립된 침실.",
      "beddingNote": "일부 매트리스는 이층 침대 상단에 있습니다. 어린이나 이동에 도움이 필요한 분이 동행한다면 사진을 확인하고 호스트에게 침구 구성을 문의해 주세요. 최종 정원은 에어비앤비에서 확인해 주세요.",
      "bathroomTitle": "욕실 2개",
      "bathroomCopy": "여럿이 함께하는 아침에도 편안하도록 욕실 2개를 갖췄습니다.",
      "tubFeatureTitle": "나만의 여유를 위한 자쿠지",
      "tubFeatureCopy": "따뜻한 나무와 은은한 조명으로 둘러싸인 넓은 전용 욕조에서 쉬어가세요.",
      "diningFeatureTitle": "다시 모이게 되는 식탁",
      "dining201Copy": "넉넉한 식탁에 의자 8개와 추가 의자 4개가 준비되어 있습니다.",
      "dining202Copy": "의자 6개와 추가 스툴이 있는 식탁에서 함께 시간을 보내세요.",
      "kitchenEquipmentTitle": "가벼운 아침을 위한 주방",
      "kitchenEquipmentCopy": "인덕션, 전자레인지, 냉장고, 정수기를 갖췄으며 간단한 조리가 가능합니다.",
      "comfortTitle": "일상의 편안함",
      "comfort201Copy": "65인치 TV, 에어컨, 세탁기와 건조기, 캡슐 커피 머신이 준비되어 있습니다.",
      "comfort202Copy": "55인치 TV, 에어컨, 세탁기와 건조기가 준비되어 있습니다.",
      "checkInLabel": "체크인",
      "checkOutLabel": "체크아웃",
      "arrivalGuide": "셀프 체크인이 가능합니다. 도착 안내는 에어비앤비를 통해 전달됩니다. 특별한 도착 요청이 있다면 예약 전 호스트에게 문의해 주세요.",
      "houseRulesTitle": "서로를 배려하는 머무름.",
      "ruleQuiet": "오후 9시 이후에는 소음을 줄여 주세요. 파티는 허용되지 않습니다.",
      "ruleSmoke": "실내 금연이며 반려동물은 동반할 수 없습니다.",
      "ruleCooking": "간단한 조리만 가능합니다. 자세한 주방 이용 규칙은 에어비앤비에서 확인해 주세요.",
      "ruleSecurity": "입구에 보안용 CCTV가 설치되어 있습니다. 자세한 내용은 에어비앤비에서 확인해 주세요.",
      "chooseMapStay": "위치를 확인할 숙소를 선택하세요",
      "locationHeading": "숙소 위치",
      "viewStayLocation": "이 숙소 위치 보기",
      "locationExact": "숙소 위치",
      "locationArea": "대략적인 지역",
      "locationPending": "위치 정보 준비 중",
      "locationSoon": "위치 공개 예정",
      "mapPending": "위치 정보를 준비하고 있습니다. 먼저 이 숙소의 에어비앤비에서 주변 지역을 확인해 주세요.",
      "mapSoon": "새로운 주소에서 시작될 이야기. 오픈 소식과 함께 위치를 공개할 예정입니다.",
      "mapExactNote": "선택한 숙소의 위치입니다. 출입구 등 자세한 도착 안내는 에어비앤비 메시지를 확인해 주세요.",
      "mapAreaNote": "선택한 숙소의 대략적인 주변 지역이며 정확한 주소는 아닙니다. 도착 안내는 예약 후 에어비앤비를 통해 전달됩니다.",
      "mapPendingNote": "이 숙소의 정확한 위치는 아직 이곳에 공개되지 않았습니다. 도착 안내는 호스트가 에어비앤비로 전달합니다.",
      "mapAirbnb": "에어비앤비에서 위치 확인"
    }
  }
};
